upstream octane_app {
    server app:8000;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/public;

    charset utf-8;

    location / {
        # REMOVIDO o "$uri/" para evitar o erro 403 na raiz do projeto
        try_files $uri @octane;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/error.log error;

    location @octane {
        proxy_pass http://octane_app;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ /\.ht {
        deny all;
    }
}
